---
output: 
  github_document:
    html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

<!-- badges: start -->
<!-- badges: end -->

# err

Error handling for R, inspired by Go's standard library.

## Installation

``` r
# install.packages("remotes")
remotes::install_github("devOpifex/err")
```

## Examples

Errors and warning can either be created from strings or warning and error objects.

```{r}
library(err)

err <- e("Something went wrong")

foo <- function(...){
  tryCatch(
    ..., 
    error = function(err) e(err), 
    warning = function(war) w(war) 
  )
}

foo(log("a"))
foo(matrix(1:3, nrow = 2))
```

Templates that are used to print errors and warnings can be customised.

```{r}
tmpl.e("Whoops: %s - sorry!")

e("Sumin' went wrong")
```

You can also retrieve the message of the error or warning.

```{r}
err <- e("Argh")
war <- w("Careful")

err$error()
war$warning()
```

One can check whether the object returned is an error or a warning.

```{r}
x <- tryCatch(print(error), error = function(err) e(err))

is.e(x)
```
